name: CI

on:
    push:
        branches:
            - master
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - uses: actions/setup-node@v2
              with:
                  cache: 'pnpm'
                  node-version: 18

            - run: pnpm install

            - run: pnpm run build

            - run: npx tsc --project tsconfig.node.json

    eslint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - uses: actions/setup-node@v2
              with:
                  cache: 'pnpm'
                  node-version: 18

            - run: pnpm install

            - run: npx eslint

    typings:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3

            - uses: actions/setup-node@v2
              with:
                  cache: 'pnpm'
                  node-version: 18

            - run: pnpm install

            - run: npx tsc --noEmit

            - run: npx tsc --noEmit -p tsconfig.node.json
